#!/bin/sh

set -e

if [ "$1" = 'vscode-install-extension' ]; then
    rm -rf ~/.vscode/extensions/plang
    cp -r plang ~/.vscode/extensions/plang

elif [ "$1" = 'nim' ]; then
    cd vm/nim
    nim c main.nim

    echo
    ./main $2

elif [ "$1" = 'nim-test' ]; then
    cd vm/nim
    nim c -d:release main.nim
    cd ../../

    for file in examples/*; do
        echo "---------------------------------"
        echo "Testing $file"
        ./vm/nim/main $file
    done
    echo "---------------------------------"
    
else
    "$@"
fi